apiVersion: v1
kind: PresistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce    # suitable for EBS AWS Storage Type
  storageClassName: mysql-sc
  resources:
    requests:
      storage: 5Gi
