apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-efs-pv
spec:
  storageClassName: efs-sc
  capacity:
    storage: 5Gi
    volumeMode: FileSystem
  accessModes:
    - ReadWriteMany      # many requests from more than pod
  presistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <fs-iu132d8d9a>::<fsap-iu21h3i21>    # filesystem id:: access point id

