apiVersion: v1
kind: PresistentVolumeClaim
metadata:
  name: wordpress-efs-pvc
spec:
  accessModes:
    - ReadWriteMany    # suitable for EFS AWS Storage Type
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
